### ISSUE TITLE
Actif déplié déborde

### ISSUE THREAD

**Issue by pinage404** [laem/politix#1]
Salut,

Bravo pour ce nouveau projet !

Lorsque je clique sur `Actif`, la date dépasse de la boite, avec texte blanc sur fond blanc

![example](https://github.com/user-attachments/assets/a9d0a5b9-8c65-44d5-9300-fac982fcecdb)

Observé sur Zen Browser : 1.0.2-b.5 (Firefox 133.0.3) (64 bits)

**Comment by laem** [comment]
Oui, noté aussi, j'avais pas le temps de trouver une solution pour sans JS ^^

**Comment by pinage404** [comment]
Ok, je vais tenter une PR
